GameState.layouts.titleMode = {
	"titleMenu":{
		"title_text":{
			txt:"Super EvoDoctor Deluxe",
			size:50,
			color:"#BBC000",
			x:0,
			y:40,
			hitbox:"play"
		},
		"play_button":{
			txt:"Play",
			size:40,
			valign:"middle",
			x:0,
			y:-70,
			hitbox:"play"
		},
		"options_button":{
			txt:"Options",
			size:40,
			valign:"middle",
			x:0,
			y:-20,
			hitbox:"options"
		},
		"help_button":{
			txt:"Help",
			size:40,
			valign:"middle",
			x:0,
			y:30,
			hitbox:"help"
		},
		"about_button":{
			txt:"About",
			size:40,
			valign:"middle",
			x:0,
			y:80,
			hitbox:"about"
		}
	},
	"titleOptions":{
		"fullscreen_button":{
			txt:"Fullscreen",
			size:35,
			valign:"middle",
			x:0,
			y:-20,
			hitbox:"fullscreen"
		},
		"actual_button":{
			txt:"Actual Size",
			size:35,
			valign:"middle",
			x:0,
			y:20,
			hitbox:"actual"
		},
		"back_button":{
			txt:"< Back",
			size:28,
			valign:"middle",
			x:-230,
			y:0,
			hitbox:"back"
		}
	},
	"titleHelp":{
		"help_text":{
			txt:"In this game, you play the role of a doctor who has been assigned to control an outbreak of a deadly disease. When you kill bacteria inside of your patient, they will evolve and adapt to the way that you're killing them. You have antibiotics at your disposal, but you must be careful to use antibiotics responsibly! If you overuse your antibiotics, the bacteria will grow resistant to them, and you risk triggering a global pandemic that will wipe out the world!",
			halign:"left",
			textbox:400,
			size:20,
			x:-130,
			y:50
		},
		"back_button":{
			txt:"< Back",
			size:28,
			valign:"middle",
			x:-230,
			y:0,
			hitbox:"back"
		}
	},
	"titleAbout":{
		"about_text":{
			txt:"This game is the brainchild of Fedor Kondrashov, who is a laboratory leader at the Center for Genomics Research in Barcelona, Spain. It is an educational tool for demonstrating the processes of selection and evolution in a real system.",
			halign:"left",
			textbox:400,
			size:20,
			x:-130,
			y:50
		},
		"back_button":{
			txt:"< Back",
			size:28,
			valign:"middle",
			x:-230,
			y:0,
			hitbox:"back"
		}
	}
}